apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: memory-scaledobject
spec:
  scaleTargetRef:
    name: dev-hello-app
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: memory
    metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    metadata:
      value: "10"